### ISSUE TITLE
新版本的decompress.py输出文件无后缀

### ISSUE THREAD

**Issue by Dragon-ts** [7aGiven/Phigros_Resource#2]
当config.ini的music选项为true时,输出的不是`.wav`格式,而是无后缀,但手动添加后缀即可以播放
![0](https://github.com/7aGiven/Phigros_Resource/assets/106637358/7251538b-2ade-46e3-b450-e0ca09ab4deb)

**Comment by Dragon-ts** [comment]
召唤文酱！召唤文酱！召唤文酱！召唤文酱！召唤文酱！召唤文酱！召唤文酱！召唤文酱！召唤文酱！召唤文酱！召唤文酱！

**Comment by 7aGiven** [comment]
8月5日更新，已解决该issue
