### ISSUE TITLE
[?]decompress.py在python3.11下无法使用(?

### ISSUE THREAD

**Issue by Dragon-ts** [7aGiven/Phigros_Resource#3]
使用3.10不会报错,但是3.11会报错
`Traceback (most recent call last):
  File "D:\3.0.1\decompress.py", line 98, in <module>
    index = key.rindex("/")
            ^^^^^^^^^^^^^^^
ValueError: substring not found`

不排除个人因素的可能

**Comment by 7aGiven** [comment]
电脑上暂时没有3.11版python，有时间进行测试。

**Comment by 7aGiven** [comment]
> 使用3.10不会报错,但是3.11会报错 `Traceback (most recent call last): File "D:\3.0.1\decompress.py", line 98, in <module> index = key.rindex("/") ^^^^^^^^^^^^^^^ ValueError: substring not found`
> 
> 不排除个人因素的可能

已取消bundle的decompress步骤，如果有时间请帮助于Python 3.11测试。
